### ISSUE TITLE
As a facilitator, I want to be able to share my rooms calendar so that tandem can schedule mentors/members based on rooms

### ISSUE THREAD

**Issue by Zandrr** [BeTandem/scheduler_frontend#19]

**Comment by sthoma** [comment]
So just to clarify --  this is the page for the "Room Availability" navbar link. And the only thing it needs to contain is a field for the facilitator to enter a sharing URL for their rooms calendar?

Or do we need multiple fields (or ability to add more fields) for multiple rooms each with their own calendar?

@thejinxters @Zandrr

**Comment by thejinxters** [comment]
I would think multiple rooms. Perhaps you can just make 5 fields for that, but in the future i think it would be neat if we could add more fields with a button click.

**Comment by thejinxters** [comment]
@sthoma There was one problem with this PR, (something that was a problem from before). When you add something, then click delete it will not delete. This is because when the room is added to the list, it is not given an ID number, and that is needed to delete it from the DB. 

**Solution**: The route now returns the object (with fields _id, name, calendarUrl... whatever was passed to the route). So instead of storing the `newRoom` object into the `$scope.rooms`, instead return the result of the promise. (just add a var that is injected into the anonymous function)

**Comment by sthoma** [comment]
@thejinxters #31 should resolve this. Want me to throw up a PR fixing this in the mentor controller?
